title: "Marcus Francisco | ePortfolio"
description: "A portfolio showcasing my Electrical Engineering projects, coursework, and reflections."
baseurl: "" # Leave empty for GitHub Pages
url: "https://marcusfrancisco.github.io" # Custom domain when set
theme: minima # Default Jekyll theme (can be changed)